# Generated by Django 5.1.4 on 2024-12-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="U_id",
            field=models.CharField(default="", max_length=10, unique=True),
        ),
    ]
