# Generated by Django 5.1.4 on 2024-12-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_question_u_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="U_id",
            field=models.CharField(default="", max_length=10),
        ),
    ]
