# Generated by Django 5.1.4 on 2024-12-16 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_question_u_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="is_default",
        ),
    ]
