# Generated by Django 5.1.4 on 2024-12-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_question_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
