# Generated by Django 5.1.4 on 2024-12-17 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_usersubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="current_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.question",
            ),
        ),
    ]
